# Generated by Django 2.2.7 on 2020-01-26 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Keys',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_name', models.CharField(default=None, max_length=100)),
                ('privateKey_1', models.CharField(default=None, max_length=500)),
                ('privateKey_2', models.CharField(default=None, max_length=500)),
                ('publicKey', models.CharField(default=None, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Components',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component_name', models.CharField(default=None, max_length=100)),
                ('component_quantity', models.CharField(default=None, max_length=100)),
                ('component_cost', models.CharField(default=None, max_length=10)),
                ('key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='files.Keys')),
            ],
        ),
    ]
