# Generated by Django 2.2.7 on 2020-01-26 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Components',
            new_name='Component',
        ),
        migrations.RenameModel(
            old_name='Keys',
            new_name='Key',
        ),
    ]
