# Generated by Django 2.2.7 on 2020-01-28 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_auto_20200127_0103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='component_cost',
            field=models.CharField(default=None, max_length=500),
        ),
        migrations.AlterField(
            model_name='component',
            name='component_name',
            field=models.CharField(default=None, max_length=500),
        ),
        migrations.AlterField(
            model_name='component',
            name='component_quantity',
            field=models.CharField(default=None, max_length=500),
        ),
    ]
