# Generated by Django 3.0.3 on 2020-02-21 13:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('files', '0004_auto_20200221_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='key',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='files.Medicine'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='manager',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
