# Generated by Django 3.0.3 on 2020-03-05 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0007_auto_20200305_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='component_cost',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='component',
            name='component_quantity',
            field=models.BigIntegerField(default=0),
        ),
    ]
