# Generated by Django 3.0.3 on 2020-03-05 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0008_auto_20200305_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='component_cost',
            field=models.CharField(default=None, max_length=500),
        ),
        migrations.AlterField(
            model_name='component',
            name='component_quantity',
            field=models.CharField(default=None, max_length=500),
        ),
    ]
