# Generated by Django 3.0.3 on 2020-03-12 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0009_auto_20200306_0008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='component_name',
            field=models.BinaryField(default=None),
        ),
    ]
