# Generated by Django 2.2.7 on 2020-04-01 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0014_auto_20200331_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='email',
            field=models.EmailField(default=None, max_length=100, unique=True),
        ),
    ]
