# Generated by Django 2.2.7 on 2020-04-02 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0015_auto_20200401_1925'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='key',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='files.Medicine'),
        ),
        migrations.AddField(
            model_name='employee',
            name='medicine_name',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
