# Generated by Django 2.2.7 on 2020-04-13 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0017_logs'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Logs',
            new_name='Log',
        ),
    ]
